shop_project/contact_app/urls.py
from django.urls import path
from . import views

app_name = 'contact_app'

urlpatterns = [
  path('', views.contact, name='contact'),
  path('contact_succes/', views.contact_succes, name=contact_succes)


]

shop_project/shop_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
  path('', views.index, name='index'),
  path('products/<int:product_id>', views.product, name='product'),
  path('customers/', views.customers, name='customers'),
  path('customers/<int:customer_id>', views.customer, name='customer'),
  path('products/<int:product_id>/comment_form', views.comment_form, name='comment_form'),



]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop_app/', include('shop_app.urls')),
]

shop_project/contact_app/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
	subject = models.CharField(max_length=264)
	email = models.EmailField()
	text = models.TextField()
 
  def __str__(self):
    return self.subject

  def __repr__(self):
    return "<Contact {}>".format(self.subject)

shop_project/shop_app/models.py
from django.db import models

class Product(models.Model):
  name = models.CharField(max_length=264)
  price = models.DecimalField(max_digits=5, decimal_places=2)
  description = models.TextField()
  image = models.ImageField(default='static/images/image.png', upload_to='static/images/')

  def __str__(self):
    return self.name

  # def __repr__(self):
  #   return "<Product {}>".format(self.name)


class Customer(models.Model):
  first_name = models.CharField(max_length=264)
  last_name = models.CharField(max_length=264)
  email = models.EmailField(max_length=264)
  password = models.CharField(max_length=264)
  profile_picture = models.ImageField(default='static/images/profile.jpg', upload_to='static/images/profile_pictures/')

  def __str__(self):
    return self.email

  def __repr__(self):
    return "<Customer {}>".format(self.email)

class Comment(models.Model):
  username = models.CharField(max_length=264)
  text = models.TextField()
  date = models.DateField()
  product = models.ForeignKey(Product, on_delete=models.CASCADE)


  def __str__(self):
    return self.username

  def __repr__(self):
    return "<Comment {}>".format(self.username)


    

shop_project/contact_app/forms.py
from django import forms
from contact_app.models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = ['subject', 'email', 'text']
		widgets = {
		'subject': forms.TextInput(attrs={
			'id': 'contact-subject', 
			'placeholder': 'subject',
			'required': True
			}),
		'email': forms.EmailInput(attrs={
			'id': 'contact-email', 
			'placeholder': 'email',
			'required': True
			}),
		'text': forms.Textarea(attrs={
			'id': 'contact-text',
			'placeholder': 'Write a comment here ...',
			'required':True
			}),
		}

shop_project/shop_app/forms.py
from django import forms
from shop_app.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['username', 'text']
		widgets = {
		'username': forms.TextInput(attrs={
			'id': 'comment-username', 
			'placeholder': 'username',
			'required': True
			}),
		'text': forms.Textarea(attrs={
			'id': 'comment-text',
			'placeholder': 'Write a comment here ...',
			'required':True
			}),
		}

shop_project/contact_app/views.py
from django.shortcuts import render, redirect
from contact_app.forms import ContactForm
from contact_app.models import Contact 



def contact(request):
	if request.method == 'POST':
		subject = request.POST.get('subject')
		email = request.POST.get('email')
		text = request.POST.get('text')
		Contact.objects.get_or_creat(subject=subject, email=email, text=text)
		
	return render(request, 'contact.html', context={ 'contact_form': ContactForm() })[0],
	return redirect('contact_succes/' )


def contact_succes(request)
	return render(request, 'contact_succes.html')

shop_project/shop_app/views.py
from django.shortcuts import render
from shop_app.models import Product, Customer, Comment
from shop_app.forms import CommentForm 
import datetime


def index(request):
  products = Product.objects.all()
  return render(request, 'index.html', context={ 'products': products })


def product(request, product_id):
  product = Product.objects.get(id=product_id)
  comments = Comment.objects.all().filter(product_id=product_id)
  return render(request, 'product.html', context={ 'product': product,'comments': comments })


def customers(request):
  customers = Customer.objects.all()
  return render(request, 'customers.html', context={ 'customers': customers })


def customer(request, customer_id):
  customer = Customer.objects.get(id=customer_id)
  return render(request, 'customer.html', context={ 'customer': customer, 'comment': comment })


def comment_form(request, product_id):
	if request.method == 'POST':
		username = request.POST.get('username')
		text = request.POST.get('text')
		product = Product.objects.get(id=product_id)
		date = datetime.datetime.now()
		Comment.objects.get_or_create(username=username, text=text, date=date, product=product)[0]
		

	return render(request, 'comment_form.html', context={ 'comment_form': CommentForm() } )

shop_project/contact_app/templates/contact.html
<!DOCTYPE html>
<html>
<head>
	<title>Contact Us</title>
</head>
<body>

	<h1> Ajoutez un contact</h1>

	<form action="contact_form" method="POST">
		{{ contact_form.as_p }} 
		{% csrf_token %}
		<input type="submit" name="submit" valur="send comment">
	</form>
		}

</body>
</html>

shop_project/contact_app/templates/contact_succes.html
<!DOCTYPE html>
<html>
<head>
	<title>Merci de votre inscription</title>
</head>
<body>
	<h1>Great Inscription </h1>

</body>
</html>

shop_project/shop_app/templates/comment_form.html
<!DOCTYPE html>
<html>
<head>
	<title>Add a new Comment</title>
</head>
<body>

	<h1> Ajoutez un commentaire</h1>

	<form action="comment_form" method="POST">
		{{ comment_form.as_p }} 
		{% csrf_token %}
		<input type="submit" name="submit" valur="send comment">
	</form>
		}

</body>
</html>

shop_project/shop_app/templates/customer.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <title>{{ customer.first_name }} {{ customer.last_name }}</title>
</head>
<body>

  <h1>{{ customer.first_name }} {{ customer.last_name }}</h1>
  <p>{{ customer.email }}</p>
  <img src="http://{{ request.get_host }}/{{ customer.profile_picture }}">

</body>
</html>

shop_project/shop_app/templates/customers.html
<!DOCTYPE html>
<html>
<head>
  <title>Customers</title>
</head>
<body>

  {% for customer in customers %}
    <h3>{{ customer.first_name }} {{ customer.last_name }}</h3>
    <a href="{% url 'shop_app:customer' customer.id %}">{{ customer.email }}</a>
  {% endfor %}

</body>
</html>

shop_project/shop_app/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Home Page</title>
</head>
<body>

  <h1>Product List</h1>

  {% for product in products %}
    <h3>{{ product.name }} - ${{ product.price }}</h3>
    <p>{{ product.description }}</p>
    <a href="{% url 'shop_app:product' product.id %}">click here</a>
    <hr>
  {% endfor %}

</body>
</html>

shop_project/shop_app/templates/maillot.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <title>{{ maillot.name }} {{ maillot.description }}</title>
</head>
<body>

  <h1>{{ maillot.name }} {{ maillot.description }}</h1>
  <p>{{ maillot.price }}</p>
  <img src="http://{{ request.get_host }}/{{ maillot.profile_picture }}">

</body>
</html>

shop_project/shop_app/templates/maillots.html
<!DOCTYPE html>
<html>
<head>
  <title>Maillots</title>
</head>
<body>

  {% for maillot in maillots %}
    <h3>{{ maillot.name }} {{ maillot.description }}</h3>
    <!-- <a href="{% url 'shop_app:maillot' maillot.id %}"> --><p>{{ maillot.price }}</p>
  {% endfor %}

</body>
</html>

shop_project/shop_app/templates/product.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>{{ product.name }}</title>
</head>
<body>
	<h1> Product Details</h1>
	<img src="http://{{request.get_host }}/{{ product.image }}">
	<h3>Name: {{ product.name }}</h3>
	<h3>Price: {{ product.price }}</h3>
	<h3>Description : {{ product.description }}</h3>

<h1>Comment</h1>
	{% for comment in comments %}
	<a href="#"></a>
		<h3> {{ comment.username }} </h3>
		<p> {{ comment.text }} </p>
		
		{% endfor %}
	}
}
}
  
</body>
</html>